theme: jekyll-theme-cayman

# Site setting
title: Jinghua Wang
SEOTitle: Jinghua Wang | UW CSE Studnet
email: johnjinghuawang@gmail.com
descrpition: Fuse techonolgy with human concerns
keyword: "John Wang, Jinghua Wang, 王靖华, UW, CSE, web developer, software developer"
