theme: jekyll-theme-cayman

# Site setting
title: Jinghua Wang
subtitle: Combine techonolgy with human concerns
SEOTitle: Jinghua Wang | UW CSE Studnet
email: johnjinghuawang@gmail.com
keyword: "John Wang, Jinghua Wang, 王靖华, UW, CSE, web developer, software developer"
